### ISSUE TITLE
Doesn't seem to work for react native

### ISSUE THREAD

**Issue by Twos22** [FormidableLabs/prism-react-renderer#147] opened 2022-03-23 21:53 UTC
Hi,

it seems this doesn't work for react native (anymore?). I wasn't able to get it run at least. Could you possibly add some guidence to the readme?

Thanks
Twos

**Comment by narinluangrath** [comment] 2022-08-26 17:57
Hi @Twos22, I was able to getting it running. I'm closing this issue until you can provide a reproduction. Since `prism-react-renderer` leaves the actual rendering to the consumer (via render props) there's no reason it shouldn't work with React Native. Instead of using `<div>`s and `<span>`s just use their React Native counterparts `<View>` and `<Text>`. 

Here's a demo: https://snack.expo.dev/mPccGEz-a
![image](https://user-images.githubusercontent.com/13155517/186963301-dd8b9e20-2ab4-4428-a0a7-92793cf59819.png)

**Closed by narinluangrath** 2022-08-26 17:57 UTC
